### ISSUE TITLE
键盘阻塞

### ISSUE THREAD

**Issue by rainssong** [f111fei/2048egret#3]
快速交替按横向竖向键后者会被覆盖

**Comment by f111fei** [comment]
这是故意的，就是为了防止过快移动。移动间隔是150ms， 具体的代码参照https://github.com/f111fei/2048egret/blob/master/src/org/xzper/view/ApplicationMediator.ts 的109行

**Comment by rainssong** [comment]
噢，谢谢。原版没有该机制，故问
